# Generated by Django 3.1.7 on 2021-03-01 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_album_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
