# Generated by Django 3.1.7 on 2021-03-01 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_artist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='name',
            new_name='artist',
        ),
    ]
