# Generated by Django 3.1.7 on 2021-03-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210301_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='artwork',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
