# Generated by Django 3.1.7 on 2021-03-03 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_album_artwork'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='artwork',
            new_name='photo',
        ),
    ]
